### ISSUE TITLE
npm scripts

### ISSUE THREAD

**Issue by matthewdking** [fac-13/correl#56]
npm `start` is a script that is used to start the project on hosting sites such as heroku, therefore I would advise having it not using nodemon and create a separate script for your dev set up.

Similarly this is something you haven't encountered yet but the `build` script is often used to build a production version of your site. Eg compile down ready to be deployed. Therefore the build script currently for building the db I would possibly rename to `db-build` or something similar. (This last point is less important so take it or leave it 🤷‍♂️ )

**Comment by tspeed90** [comment]
@matthewdking SO USEFUL. Thank you!
