### ISSUE TITLE
Technical Spikes

### ISSUE THREAD

**Issue by tspeed90** [fac-13/correl#9]
30 minutes on Mocha/Chai and creating a scale (d3?)

**Comment by eadehemingway** [comment]
https://www.w3schools.com/howto/howto_js_rangeslider.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by tspeed90** [comment]
Mocha/Chai: https://hackmd.io/3U8LMOtSTEifnekvpYW_vQ
Using Mocha with Supertest: http://willi.am/node-mocha-supertest/

A few example Mocha/Chai tests:

```js
describe('mocha basics', () => {
  it('true should be true', () => {
    true.should.be.true;  
  });
  it('true should be true', () => {
    expect(true).to.be.true;
  })
})

describe('Math', () => {
  it('3*3 should equal 9', () => {
    assert.equal(9, 3*3);
  });
  it('(3-4)*8=-8', () => {
    assert.equal(-8, (3-4)*8);
  })
});
```

**Comment by tspeed90** [comment]
Supertest docs: https://www.npmjs.com/package/supertest
